# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = DeviceClient
DESTDIR = ../x64/Debug
QT += widgets network
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./DeviceClient.h
SOURCES += ./DeviceClient.cpp \
    ./main.cpp
FORMS += ./DeviceClient.ui
RESOURCES += DeviceClient.qrc
